### ISSUE TITLE
CUDA kernel failed : invalid device function

### ISSUE THREAD

**Issue by MingyeXu** [zeliu98/CloserLook3D#22]
Thanks for the code so much. Have you meet the following problem?

CUDA kernel failed : invalid device function
void masked_ordered_query_ball_point_kernel_wrapper(int, int, int, float, int, const float*, const float*, const int*, const int*, int*, int*, float*, int*) at L:109 in _ext_src/src/masked_ordered_ball_query_gpu.cu
CUDA kernel failed : invalid device function
void masked_ordered_query_ball_point_kernel_wrapper(int, int, int, float, int, const float*, const float*, const int*, const int*, int*, int*, float*, int*) at L:109 in _ext_src/src/masked_ordered_ball_query_gpu.cu
CUDA kernel failed : invalid device function
void masked_ordered_query_ball_point_kernel_wrapper(int, int, int, float, int, const float*, const float*, const int*, const int*, int*, int*, float*, int*) at L:109 in _ext_src/src/masked_ordered_ball_query_gpu.cu
CUDA kernel failed : invalid device function
void masked_ordered_query_ball_point_kernel_wrapper(int, int, int, float, int, const float*, const float*, const int*, const int*, int*, int*, float*, int*) at L:109 in _ext_src/src/masked_ordered_ball_query_gpu.cu
Traceback (most recent call last):
  File "/home/xumingye/anaconda2/envs/pytorch_1.4/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xumingye/anaconda2/envs/pytorch_1.4/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xumingye/anaconda2/envs/pytorch_1.4/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/xumingye/anaconda2/envs/pytorch_1.4/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)

**Comment by zeliu98** [comment]
Hi @MingyeXu,
This may cause by the lack of GPU memory, can you reduce the batch size and try again?

**Comment by MingyeXu** [comment]
Thank you so much, I'll try it.
