### ISSUE TITLE
Error :Could not import _ext module. 

### ISSUE THREAD

**Issue by yeminglang** [zeliu98/CloserLook3D#37]
Dear @zeliu98 
Thank you for your code.Here I meet a problem:(Could not import _ext module. )while training. (shown as below)

`Traceback (most recent call last):
  File "function/train_s3dis_dist.py", line 24, in <module>
    from models import build_scene_segmentation
  File "/home/yeminglang/project/CloserLook3D/pytorch/models/__init__.py", line 1, in <module>
    from .build import build_classification, build_multi_part_segmentation, build_scene_segmentation
  File "/home/yeminglang/project/CloserLook3D/pytorch/models/build.py", line 4, in <module>
    from .backbones import ResNet
  File "/home/yeminglang/project/CloserLook3D/pytorch/models/backbones/__init__.py", line 1, in <module>
    from .resnet import ResNet
  File "/home/yeminglang/project/CloserLook3D/pytorch/models/backbones/resnet.py", line 3, in <module>
    from ..local_aggregation_operators import LocalAggregation
  File "/home/yeminglang/project/CloserLook3D/pytorch/models/local_aggregation_operators.py", line 13, in <module>
    from pt_utils import MaskedQueryAndGroup
  File "/home/yeminglang/project/CloserLook3D/pytorch/ops/pt_custom_ops/pt_utils.py", line 10, in <module>
    "Could not import _ext module.\n"
ImportError: Could not import _ext module.
Please see the setup instructions in the README: https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/README.rst`

Can this problem be solved by 
pip install "git+git://github.com/erikwijmans/Pointnet2_PyTorch.git#egg=pointnet2_ops&subdirectory=pointnet2_ops_lib" ?
I have no idea because I can't download this package properly :( ...
Or there is another things going wrong?

python=3.6
pytorch=1.5
cuda=10.1
pillow=6.2.1

Your prompt reply is looking forward!

Best wish!
Your sincere : yeminglang

**Comment by Madeline-hyh** [comment]
I have the same problem, have you solved it？
