### ISSUE TITLE
bugs in tf

### ISSUE THREAD

**Issue by cuge1995** [zeliu98/CloserLook3D#9]
```shell
running build_ext
Traceback (most recent call last):
  File "/anaconda3/envs/closelook3d/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/public/home/jx_zjl/anaconda3/envs/closelook3d/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/public/home/jx_zjl/anaconda3/envs/closelook3d/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/public/home/jx_zjl/anaconda3/envs/closelook3d/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/public/home/jx_zjl/anaconda3/envs/closelook3d/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:
```

**Comment by cuge1995** [comment]
the env is the same of your provided

**Comment by cuge1995** [comment]
close because under Slurm Workload Manager
